# Generated by Django 5.0.2 on 2024-02-29 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_review_created_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 16, 46, 37, 454936)),
        ),
    ]
